#!/usr/bin/env node

/**
 * OpenAPI → TypeScript 타입 자동 생성 스크립트
 * OS 무관 (Windows cmd/powershell/bash 모두 지원)
 *
 * Usage:
 *   node scripts/generate-types.mjs
 *   node scripts/generate-types.mjs --url http://localhost:8080/api/docs/openapi
 *   node scripts/generate-types.mjs --out src/lib/api-types.ts
 *   OPENAPI_URL=http://... node scripts/generate-types.mjs
 *
 * 정책: 생성 파일은 커밋 대상 (백엔드 미실행 환경에서도 프론트 빌드 보장)
 */

import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const frontendRoot = resolve(__dirname, '..');

function getArg(name) {
  const idx = process.argv.indexOf(name);
  return idx !== -1 && process.argv[idx + 1] ? process.argv[idx + 1] : null;
}

const url = getArg('--url') || process.env.OPENAPI_URL || 'http://localhost:8080/api/docs/openapi';
const outputPath = resolve(frontendRoot, getArg('--out') || 'src/lib/api-types.ts');

// 로컬 바이너리 우선 (node_modules/.bin), 없으면 npx fallback
const localBin = resolve(frontendRoot, 'node_modules/.bin/openapi-typescript');
const cmd = existsSync(localBin)
  ? `"${localBin}" "${url}" -o "${outputPath}"`
  : `npx openapi-typescript "${url}" -o "${outputPath}"`;

console.log(`[generate-types] Source: ${url}`);
console.log(`[generate-types] Output: ${outputPath}`);

try {
  execSync(cmd, { stdio: 'inherit', cwd: frontendRoot });

  // AUTO-GENERATED 헤더 삽입
  const content = readFileSync(outputPath, 'utf-8');
  const header = [
    '/**',
    ' * AUTO-GENERATED by scripts/generate-types.mjs',
    ` * Source: ${url}`,
    ` * Generated at: ${new Date().toISOString()}`,
    ' *',
    ' * 이 파일을 직접 수정하지 마세요. 변경이 필요하면:',
    ' *   1. 백엔드 API를 수정한 후',
    ' *   2. npm run generate-types 를 실행하세요.',
    ' */',
    '',
  ].join('\n');

  if (!content.startsWith('/**\n * AUTO-GENERATED')) {
    writeFileSync(outputPath, header + content, 'utf-8');
  }

  console.log('[generate-types] Done. Commit the generated file.');
} catch (err) {
  console.error('[generate-types] Failed. Is the backend running?');
  console.error('[generate-types] Tip: OPENAPI_URL=<url> npm run generate-types');
  process.exit(1);
}

